name: Upload file

on:
  workflow_dispatch:

jobs:
 upload:
 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: README_uploaded
          path: README.md
